FROM pingidentity/pingfederate:12.3.3-latest

COPY PingFederate-12.3-Development.lic /opt/out/instance/server/default/conf/pingfederate.lic
COPY run.properties /opt/out/instance/server/bin/run.properties
